### ISSUE TITLE
Immediate EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by djbp** [gchilds/MTAudioProcessingTap-in-Swift#1]
I don't know if this is to do with a more recent version of Swift or anything, but as soon as the app is launched, calling '.pointee' on clientInfo?.assumingMemoryBound(to: AppDelegate.self) causes an EXC_BAD_ACCESS error, crashing the app.

I am currently running Xcode 8.2.1, Swift 3. Any thoughts?

**Comment by HHK1** [comment]
So you need to do the following:

1. Assign the client info to the storage pointer in the init callback:

    `tapStorageOut.pointee = clientInfo`

2. Retrieve your viewController (or AppDelegate, or whatever your put in the clientInfo) from the storage in your process callback

```
    let pointer = Unmanaged<ViewController>.fromOpaque(MTAudioProcessingTapGetStorage(tap))
    let vc = pointer.takeUnretainedValue()
```

**Comment by glm4** [comment]
Hey @HHK1, Im having some issues when closing the ViewController. The app crashes at `let vc = pointer.takeUnretainedValue()`. it seems that the VC was released but the tap process is still running. I have tried pausing the player and setting the `AVPlayerItem.audioMix` to nil but nothing.

**Comment by HHK1** [comment]
@glm4 Yeah that's probably a pointer issue. I haven't tried solving this (I didn't push this to a point where I had to worry about object deallocation). Take a look at this, the stop recording method should be a good start: https://rymc.io/2014/01/08/recording-live-audio-streams-on-ios/

**Comment by glm4** [comment]
Thanks @HHK1! I didn;t realized that the observer for the status keyPath was being called again and the tap processor created again.

**Comment by gchilds** [comment]
Hey all, it's like I didn't test this code at all - the cookie handling is straight up wrong AND the tap is being leaked. I've been meaning to push a fix for about a year now, but made the mistake of trying to get the code working with remote assets too.

**Comment by gchilds** [comment]
fixed the cookie passing and the tap leak

**Comment by omarojo** [comment]
Hey my code is pretty much the same as yours.
Im glad I found your github project. But Im having issues with the tap, I believe there is a leak with it. And I cant find a way to CFRelease(tap) in swift. I tried to retain it as a property in the setup process

```
var tap: Unmanaged<MTAudioProcessingTap>?
        let err = MTAudioProcessingTapCreate(kCFAllocatorDefault, &callbacks, kMTAudioProcessingTapCreationFlag_PostEffects, &tap)
        self.tap = tap
```
and later in the deinit() method of the class... I call _**self.tap.release()**_
But still.. I keep getting ocasional EXEC_BAD crashes in the *tapProcess* callback where it access the self instance

`let selfMediaInput = Unmanaged<VideoMediaInput>.fromOpaque(MTAudioProcessingTapGetStorage(tap)).takeUnretainedValue()`

it crashes right there.

**Comment by gchilds** [comment]
I don't keep a reference to the tap, but the `AVMutableAudioMix` does. When the player and mix go out of scope the tap's finalize callback gets called. Is yours being called?

If you crash accessing `clientInfo` as a class, then maybe it's because that class has been deallocated. There doesn't seem to be a way to synchronously stop a tap, so you need to guard against this situation.  The best way is probably to make `clientInfo` a structure containing a weak reference to your `selfMediaInput`, although in my last project I was in a rush & hackily set an early-out global variable.

So

  1. make sure finalize is called
  2. handle tap callback when your mediaInput/whatever has gone out of scope

**Comment by omarojo** [comment]
@gchilds I asked in StackOverflow and someone suggested something that sounds like what you are saying. 

https://stackoverflow.com/questions/53636698/mtaudioprocessingtap-exc-bad-access-doesnt-always-fire-the-finalize-callback#53637508

That solved my issue, but it definitely feels hacky.

**Comment by gchilds** [comment]
Interesting - none of the `MTAudioProcessingTap` code samples I've seen deal with cleaning up properly - I should update this code sample to use the method in that SO answer.

Anyway, all's well that ends well.
